### ISSUE TITLE
The repository url should be updated

### ISSUE THREAD

**Issue by oliverpool** [kvz/on-the-githubs#16]
Currently the repo URL (at the top, near the description) points to http://kvz.github.io/on-the-githubs/#kvz/nsfailover (which doesn't work).

It should point to https://kvz.github.io/on-the-githubs/#repos/kvz/nsfailover (the `repos/` part is missing)

**Comment by kvz** [comment]
Ah, good catch @oliverpool! Thank you for noticing - fixed
