### ISSUE TITLE
in-the-githubs: select which people to include

### ISSUE THREAD

**Issue by Acconut** [kvz/on-the-githubs#17]
A flag would be nice to define which categories you want to include. For example in the tus.io project, I would like to exclude the watchers but include the contributors and collaborators. If you agree, I will submit a PR for this.

**Comment by kvz** [comment]
If it's opt-in, I'm 💯

**Comment by kvz** [comment]
I apologize in advance for what you may encounter in this project. It's a 4 y/o jquery hackjob from right around when we launched the tus.io website 😱

**Comment by Acconut** [comment]
Haha, wish me luck :fist:

**Comment by Acconut** [comment]
Closing in favor of #18.
